#!/usr/bin/env python3
"""Emit src/cpu/cb_gen.rs."""

def main() -> None:
    arms = []
    for op in range(256):
        r = op & 7
        kind = op >> 3
        if op < 0x40:
            arms.append(f"        0x{op:02X} => cb_rot(cpu, bus, {kind}, {r}),\n")
        elif op < 0x80:
            bit = (op >> 3) & 7
            arms.append(f"        0x{op:02X} => cb_bit(cpu, bus, {bit}, {r}),\n")
        elif op < 0xC0:
            bit = (op >> 3) & 7
            arms.append(f"        0x{op:02X} => cb_res(cpu, bus, {bit}, {r}),\n")
        else:
            bit = (op >> 3) & 7
            arms.append(f"        0x{op:02X} => cb_set(cpu, bus, {bit}, {r}),\n")

    out = (
        "// @generated by tools/gen_cb.py\n"
        "use crate::bus::Bus;\n"
        "use crate::cpu::cb::cb_impl::*;\n"
        "use crate::cpu::Cpu;\n\n"
        "#[inline]\n"
        "pub fn execute_cb(cpu: &mut Cpu, bus: &mut Bus, op: u8) -> u8 {\n"
        "    match op {\n"
        + "".join(arms)
        + "    }\n}\n"
    )
    with open("src/cpu/cb_gen.rs", "w", encoding="utf-8") as f:
        f.write(out)
    print("wrote src/cpu/cb_gen.rs")


if __name__ == "__main__":
    main()
