#!/usr/bin/env python3
"""Emit src/cpu/opcodes_gen.rs with execute(opcode) match arms."""
from __future__ import annotations


def main() -> None:
    arms: dict[int, str] = {}

    def arm(op: int, s: str) -> None:
        if op in arms:
            raise SystemExit(f"duplicate opcode 0x{op:02X}")
        arms[op] = s

    # HALT
    arm(0x76, "op_halt(cpu, bus)")

    # LD r,r except 0x76
    for d in range(8):
        for s in range(8):
            opc = 0x40 | (d << 3) | s
            if opc == 0x76:
                continue
            arm(opc, f"op_ld_rr(cpu, bus, {d}, {s})")

    # LD r,d8 (includes 0x36 LD (HL),d8)
    for d in range(8):
        arm(0x06 + (d << 3), f"op_ld_r_d8(cpu, bus, {d})")

    # LD A,(BC/DE) and LD (BC/DE),A
    arm(0x0A, "op_ld_a_memrr(cpu, bus, 0)")
    arm(0x1A, "op_ld_a_memrr(cpu, bus, 1)")
    arm(0x02, "op_ld_memrr_a(cpu, bus, 0)")
    arm(0x12, "op_ld_memrr_a(cpu, bus, 1)")

    # INC/DEC r8
    for d in range(8):
        arm(0x04 + (d << 3), f"op_inc_r(cpu, bus, {d})")
        arm(0x05 + (d << 3), f"op_dec_r(cpu, bus, {d})")

    # INC/DEC/DADD/LD d16 for BC,DE,HL,SP
    for i in range(4):
        arm(0x03 + i * 0x10, f"op_inc_rr(cpu, {i})")
        arm(0x0B + i * 0x10, f"op_dec_rr(cpu, {i})")
        arm(0x01 + i * 0x10, f"op_ld_rr_d16(cpu, bus, {i})")
        arm(0x09 + i * 0x10, f"op_add_hl_rr(cpu, {i})")
        arm(0xC5 + i * 0x10, f"op_push_rr(cpu, bus, {i})")
        arm(0xC1 + i * 0x10, f"op_pop_rr(cpu, bus, {i})")

    # ALU A,r
    for ai in range(8):
        for r in range(8):
            arm(0x80 + (ai << 3) + r, f"op_alu_a_r(cpu, bus, {ai}, {r})")

    # ALU A,d8
    arm(0xC6, "op_alu_a_d8(cpu, bus, 0)")
    arm(0xCE, "op_alu_a_d8(cpu, bus, 1)")
    arm(0xD6, "op_alu_a_d8(cpu, bus, 2)")
    arm(0xDE, "op_alu_a_d8(cpu, bus, 3)")
    arm(0xE6, "op_alu_a_d8(cpu, bus, 4)")
    arm(0xEE, "op_alu_a_d8(cpu, bus, 5)")
    arm(0xF6, "op_alu_a_d8(cpu, bus, 6)")
    arm(0xFE, "op_alu_a_d8(cpu, bus, 7)")

    singles = {
        0x00: "op_nop()",
        0x07: "op_rlca(cpu)",
        0x0F: "op_rrca(cpu)",
        0x17: "op_rla(cpu)",
        0x1F: "op_rra(cpu)",
        0x22: "op_ld_hlp_a(cpu, bus)",
        0x2A: "op_ld_a_hlp(cpu, bus)",
        0x32: "op_ld_hlm_a(cpu, bus)",
        0x3A: "op_ld_a_hlm(cpu, bus)",
        0x27: "op_daa(cpu)",
        0x2F: "op_cpl(cpu)",
        0x37: "op_scf(cpu)",
        0x3F: "op_ccf(cpu)",
        0x08: "op_ld_nn_sp(cpu, bus)",
        0xE9: "op_jp_hl(cpu)",
        0xF9: "op_ld_sp_hl(cpu)",
        0xF3: "op_di(cpu)",
        0xFB: "op_ei(cpu)",
        0xD9: "op_reti(cpu, bus)",
        0xC9: "op_ret(cpu, bus)",
        0xE8: "op_add_sp_r8(cpu, bus)",
        0xF8: "op_ld_hl_sp_r8(cpu, bus)",
        0xC3: "op_jp_nn(cpu, bus)",
        0xCD: "op_call_nn(cpu, bus)",
        0x18: "op_jr_r8(cpu, bus)",
        0xFA: "op_ld_a_nn(cpu, bus)",
        0xEA: "op_ld_nn_a(cpu, bus)",
        0xE0: "op_ldh_n_a(cpu, bus)",
        0xF0: "op_ldh_a_n(cpu, bus)",
        0xE2: "op_ld_c_a(cpu, bus)",
        0xF2: "op_ld_a_c(cpu, bus)",
        0x10: "op_stop(cpu, bus)",
    }
    for opc, call in singles.items():
        arm(opc, call)

    # JP cc, CALL cc, RET cc (spacing is +8 between conditions)
    for i in range(4):
        arm(0xC2 + i * 8, f"op_jp_cc_nn(cpu, bus, {i})")
        arm(0xC4 + i * 8, f"op_call_cc_nn(cpu, bus, {i})")
        arm(0xC0 + i * 8, f"op_ret_cc(cpu, bus, {i})")

    # JR cc
    for i in range(4):
        arm(0x20 + i * 0x08, f"op_jr_cc_r8(cpu, bus, {i})")

    for i in range(8):
        arm(0xC7 + i * 8, f"op_rst(cpu, bus, {i * 8})")

    # Illegal / undocumented on DMG — still need deterministic cycles
    illegals = [0xD3, 0xDB, 0xDD, 0xE3, 0xE4, 0xEB, 0xEC, 0xED, 0xF4, 0xFC, 0xFD]
    for opc in illegals:
        if opc not in arms:
            arm(opc, f"op_illegal(cpu, bus, {opc})")

    # CB handled outside
    arm(0xCB, "0 /* CB: never dispatched here */")

    # Fill missing
    for opc in range(256):
        if opc not in arms:
            arm(opc, f"op_illegal(cpu, bus, {opc})")

    lines = [
        "// @generated by tools/gen_cpu_opcodes.py — DO NOT EDIT BY HAND\n",
        "use super::helpers::*;\n",
        "use super::Cpu;\n",
        "use crate::bus::Bus;\n\n",
        "#[inline]\n",
        "pub fn execute(cpu: &mut Cpu, bus: &mut Bus, opcode: u8) -> u8 {\n",
        "    match opcode {\n",
    ]
    for opc in range(256):
        lines.append(f"        0x{opc:02X} => {arms[opc]},\n")
    lines.append("    }\n}\n")

    path = "src/cpu/opcodes_gen.rs"
    with open(path, "w", encoding="utf-8") as f:
        f.write("".join(lines))
    print(f"wrote {path} ({len(arms)} arms)")


if __name__ == "__main__":
    main()
